const ActionType = {
  ADD_DEFINITION: 'ADD_DEFINITION',
  ADD_TERM: 'ADD_TERM',
  GET_DEFINITION_IDS: 'GET_DEFINITION_IDS',
  GET_LOCALE: 'GET_LOCALE',
  REMOVE_DEFINITION: 'REMOVE_DEFINITION',
  REQUEST_ADD_COMMENTS: 'REQUEST_ADD_COMMENTS', 
  REQUEST_DEFINE: 'REQUEST_DEFINE',
  REQUEST_DOWNVOTE_COMMENTS: 'REQUEST_DOWNVOTE_COMMENTS',
  REQUEST_DOWNVOTE_DEFINITIONS: 'REQUEST_DOWNVOTE_DEFINITIONS',
  REQUEST_GET_COMMENTS: 'REQUEST_GET_COMMENTS',
  REQUEST_GET_DEFINITIONS: 'REQUEST_GET_DEFINITIONS',
  REQUEST_GET_DEFINITIONS_BY_ID: 'REQUEST_GET_DEFINITIONS_BY_ID',
  REQUEST_SIGN_IN_USER: 'REQUEST_SIGN_IN_USER',
  REQUEST_SIGN_UP_USER: 'REQUEST_SIGN_UP_USER',
  REQUEST_UPVOTE_COMMENTS: 'REQUEST_UPVOTE_COMMENTS',
  REQUEST_UPVOTE_DEFINITIONS: 'REQUEST_UPVOTE_DEFINITIONS',
  SEARCH: 'SEARCH',
  TEMP: '',
};

export default ActionType;
